### PR TITLE
Deprecate canonical Multilingual Librispeech

### PR DESCRIPTION
**Pull request by polinaeterna**
Deprecate canonical Multilingual Librispeech in favor of [the community one](https://huggingface.co/datasets/facebook/multilingual_librispeech) which supports streaming.

However, there is a problem regarding new ASR template schema: since it's changed, I guess all community datasets that use this template do not work with new version of the library, including MLS. Should we somehow notify users about that or is it possible to change this line ourselves? For MLS specifically, I cannot change the code directly as I'm not the member of the Facebook org. 

Hm, and the code should be change after the release, no?

### CODE REVIEW

**Comment by lhoestq** [comment]
Yes, as discussed in #4006 we should update facebook/multilingual_librispeech indeed before we do a release. @anton-l could you help taking care of updating facebook/multilingual_librispeech ? We need to update the task template
```python
task_templates=[AutomaticSpeechRecognition(audio_column="audio", transcription_column="text")],
```
and write that `datasets>=2.1` is necessary to load it in the dataset card.

Once the change is done we can merge this PR and do the release I think

**Comment by anton-l** [comment]
@polinaeterna @lhoestq 
Updated the script and the dataset card: https://huggingface.co/datasets/facebook/multilingual_librispeech

**Comment by polinaeterna** [comment]
@anton-l @lhoestq now previewer doesn't work for this datasets as it cannot recognize new `audio_column` argument:
image

I'm not an expert in previewer things, where should I look into the corresponding code?

**Comment by severo** [comment]
Yes, there are several datasets with the same error, eg https://github.com/huggingface/datasets-preview-backend/issues/188. I'm not sure what I should do to fix this? Upgrade datasets to master?

**Comment by lhoestq** [comment]
@anton-l ended up removing the task template in facebook/multilingual_librispeech to make it work for old version of `datasets` and fix the viewer :) thanks !

**Comment by polinaeterna** [comment]
@lhoestq can we merge now? ^^

**Pull request merged**
