### PR TITLE
raise exception instead of using assertions.

### PR DESCRIPTION
**Pull request by manisnesan**
fix for the remaining files https://github.com/huggingface/datasets/issues/3171

### CODE REVIEW

**Review by mariosasko — COMMENTED** [review]
Looks good! Just added a few suggestions:

**Comment by manisnesan** [comment]
@mariosasko - Thanks for the review & suggestions. Updated as per the suggestions.

**Comment by manisnesan** [comment]
@mariosasko - Hello, Are there any additional changes required from my end??. Wondering if this PR can be merged or still pending on additional steps.

**Review by mariosasko — APPROVED** [review]
Thanks, @manisnesan.

LGTM!

**Comment by manisnesan** [comment]
@mariosasko - The approved changes in the PR now has conflicts with the master branch. Would you like me to resolve the conflicts??.  Let me know.

**Comment by manisnesan** [comment]
@mariosasko @lhoestq - Gentle reminder about my previous question.

**Comment by lhoestq** [comment]
Hi ! Thanks for the heads up :)
I just resolved the conflicts, it should be alright now

**Comment by lhoestq** [comment]
Merging, thanks for the help @manisnesan !

**Pull request merged**
