### PR TITLE
Fix: Bypass Virus Checks in Google Drive Links (CNN-DM dataset)

### LINKED ISSUE #3784: Unable to Download CNN-Dailymail Dataset
## Describe the bug
I am unable to download the CNN-Dailymail dataset. Upon closer investigation, I realised why this was happening:
- The dataset sits in Google Drive, and both the CNN and DM datasets are large.
- Google is unable to scan the folder for viruses, **so the link which would originally download the dataset, now downloads the source code of this web page:**
image
- **This leads to the following error**:
```python
NotADirectoryError: [Errno 20] Not a directory: '/root/.cache/huggingface/datasets/downloads/1bc05d24fa6dda2468e83a73cf6dc207226e01e3c48a507ea716dc0421da583b/cnn/stories'
```

## Steps to reproduce the bug
```python
import datasets
dataset = datasets.load_dataset("cnn_dailymail", "3.0.0", split="train")
```

## Expected results
That the dataset is downloaded and processed just like other datasets.

## Actual results
Hit with this error:
```python
NotADirectoryError: [Errno 20] Not a directory: '/root/.cache/huggingface/datasets/downloads/1bc05d24fa6dda2468e83a73cf6dc207226e01e3c48a507ea716dc0421da583b/cnn/stories'
```

## Environment info

- `datasets` version: 1.18.3
- Platform: Linux-5.4.144+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.12
- PyArrow version: 6.0.1

### PR DESCRIPTION
**Pull request by AngadSethi**
This commit fixes the issue described in #3784. By adding an extra parameter to the end of Google Drive links, we are able to bypass the virus check and download the datasets.

So, if the original link looked like https://drive.google.com/uc?export=download&id=0BwmD_VLjROrfTHk4NFg2SndKcjQ

The new link now looks like https://drive.google.com/uc?export=download&id=0BwmD_VLjROrfTHk4NFg2SndKcjQ&confirm=t

Fixes #3784

### CODE REVIEW

**Comment by AngadSethi** [comment]
Thank you, @albertvillanova!

**Review by albertvillanova — CHANGES_REQUESTED** [review]
Thanks for the fix.

I have just properly generated the metadata JSON file: it required not only changing the URLs¡, but running instead:
```shell
datasets-cli test datasets/cnn_dailymail --save_infos --all_configs
```

I was not able to push this change to your PR branch and I had to do it using the GitHub UI instead. Please, for future PRs, remember to allow maintainers perform changes in your PR branch. See: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

On the other hand, the tests are not passing because the dummy data should also be fixed. Once done, this PR will be able to be merged into master.

**Comment by AngadSethi** [comment]
Got it. Thanks for explaining this, @albertvillanova!

> On the other hand, the tests are not passing because the dummy data should also be fixed. Once done, this PR will be able to be merged into master.

Will do this 👍

**Comment by lhoestq** [comment]
Hi ! I think we need to fix the issue for every dataset. This can be done simply by fixing how we handle Google Drive links, see my comment https://github.com/huggingface/datasets/pull/3775#issuecomment-1050970157

**Comment by AngadSethi** [comment]
Hi @lhoestq! I think @albertvillanova has already fixed this in #3787

**Comment by lhoestq** [comment]
Cool ! I missed this one :) thanks

**Comment by AngadSethi** [comment]
No problem!

**Comment by albertvillanova** [comment]
Hi, @AngadSethi, I think that once:
- #3787 

was merged, issue:
- #3784 

was also fixed.

Therefore, I think this PR is no longer necessary. I'm closing it. Let me know if you agree.

**Comment by AngadSethi** [comment]
Yes, absolutely @albertvillanova! I agree :)

**Pull request closed without merging**
