### PR TITLE
CompGuessWhat?! 0.2.0

### PR DESCRIPTION
**Pull request by aleSuglia**
We updated some metadata information associated with the dataset. In addition, we've updated the `create_dummy_data.py` script to generate data samples for the dataset.

### CODE REVIEW

**Comment by lhoestq** [comment]
I don't see any significant change in the dataset script (except the version value update), can you check that again please ?

**Comment by lhoestq** [comment]
Hi @aleSuglia , can you check that all the changes you wanted to do are in the dataset script ?

**Comment by aleSuglia** [comment]
Hey sorry but I'm in the middle of a conference deadline. I'll let you know asap!

**Comment by lhoestq** [comment]
Ok np :)
Good luck with your work for the conference

**Comment by aleSuglia** [comment]
I finally managed to find some time to complete this. The only weird thing about this release is that I had to run the tests with the ignore checksum flag. Could it be because the Dropbox link doesn't change but the file does? Sorry didn't have the time to check the code to see what's happening behind the scenes.

**Comment by lhoestq** [comment]
Yes if the file changed, then the checksum verification won't pass as it expects to see the checksum of the old file.
The checksum is computed by hashing the complete file.
You can update the checksum by doing 

```
nlp-cli test ./datasets/compguesswhat --save_infos --all_configs
```

**Comment by aleSuglia** [comment]
Any updates on this?

**Comment by lhoestq** [comment]
Hi :)

I think what's left to do is
1- rebase from master, since we changed the name of the library
2- update the metadata file of the dataset using the command 
```
datasets-cli test ./datasets/compguesswhat --save_infos --all_configs --ignore_verifications
```

This command should update the checksum of the dropbox file

**Comment by aleSuglia** [comment]
That's perfect. I'll have a look at it later today!

**Comment by lhoestq** [comment]
Nice thanks !

**Comment by aleSuglia** [comment]
@lhoestq not sure why the quality check doesn't pass. Unfortunately CircleCI doesn't show the actual error. If I run `black` on my machine it works just fine. Ideas?

**Comment by aleSuglia** [comment]
@lhoestq any updates? :)

**Comment by lhoestq** [comment]
Your version of `black` might be outdated, our run using `black` instead of `make style` since it reformatted 100+ files.
Could you try to update black, then `make style` ?

**Comment by aleSuglia** [comment]
Yes I think my versions of isort and black were out-dated. Thanks @lhoestq :)

**Comment by lhoestq** [comment]
It still doesn't look right in terms of line-length.
Are you running `black` or `make style` ?

**Comment by aleSuglia** [comment]
I'm running `make style`. This is the output of the command:

```
black --line-length 119 --target-version py36 tests src benchmarks datasets metrics
All done! ✨ 🍰 ✨
250 files left unchanged.
isort tests src benchmarks datasets metrics
```

**Comment by lhoestq** [comment]
Weird I have the same output without file changes with black `20.8b1` and isort `5.6.4` using `make style` too

**Comment by lhoestq** [comment]
I think that's because black doesn't revert the changes you first did with the old version.
Could you open a new PR with only the ComGuessWhat files updated ? Hopefully now that black is up to date it should work directly

**Comment by aleSuglia** [comment]
I will have a look at it tomorrow. Thanks for your help!

**Comment by aleSuglia** [comment]
I'm closing this one and I'll open a new one.

**Pull request closed without merging**
