### PR TITLE
Refactor and add metadata to fever dataset

### PR DESCRIPTION
**Pull request by albertvillanova**
Related to: #4452 and #3792.

### CODE REVIEW

**Review by lhoestq — COMMENTED** [review]
Looks all good but maybe it should be in its own dataset named "feverous" ?

**Comment by albertvillanova** [comment]
But this is somehow fever v3 dataset (see this link https://fever.ai/ under the dropdown menu called Datasets). Our fever dataset already contains v1 and v2 configs. Then, this is v3 config.

**Comment by albertvillanova** [comment]
In any case, if you really think this should be a new dataset, then I would propose to create it on the Hub instead, as "fever/feverous".

**Comment by lhoestq** [comment]
> In any case, if you really think this should be a new dataset, then I would propose to create it on the Hub instead, as "fever/feverous".

Yea makes sense ! thanks :) let's push more datasets on the hub rather than on github from now on

**Pull request merged**
