### PR TITLE
[Scientific papers] Mirror datasets zip

### PR DESCRIPTION
**Pull request by patrickvonplaten**
Datasets were uploading to https://s3.amazonaws.com/datasets.huggingface.co/scientific_papers/1.1.1/arxiv-dataset.zip and https://s3.amazonaws.com/datasets.huggingface.co/scientific_papers/1.1.1/pubmed-dataset.zip respectively to escape google drive quota and enable faster download.

### CODE REVIEW

**Review by lhoestq — COMMENTED** [review]
Nice !

Could you try to reduce the size of the dummy_data.zip files ? they're quite big (300KB)

**Comment by patrickvonplaten** [comment]
> Nice !
> 
> Could you try to reduce the size of the dummy_data.zip files ? they're quite big (300KB)

Yes, I think it might make sense to enhance the tool a tiny bit to prevent this

**Comment by patrickvonplaten** [comment]
That's the lightest I can make it...it's long-range summarization so a single sample has ~11000 tokens.

**Comment by lhoestq** [comment]
Ok thanks :)

**Comment by patrickvonplaten** [comment]
Awesome good to merge for me :-)

**Review by lhoestq — APPROVED** [review]

**Pull request merged**
