### PR TITLE
Add SelQA Dataset

### PR DESCRIPTION
**Pull request by Bharat123rox**
Add the SelQA Dataset, a new benchmark for selection-based question answering tasks
Repo: https://github.com/emorynlp/selqa/
Paper: https://arxiv.org/pdf/1606.08513.pdf

### CODE REVIEW

**Comment by ijaz314** [comment]
Hii please follow me

**Review by lhoestq — APPROVED** [review]
Awesome thank you !

**Comment by lhoestq** [comment]
The CI error `FAILED tests/test_file_utils.py::TempSeedTest::test_tensorflow` is not related with this dataset and is fixed on master. You can ignore it

**Comment by lhoestq** [comment]
merging since the Ci is fixed on master

**Pull request merged**
