### PR TITLE
Fix filter indices when batched

### LINKED ISSUE #5112: Bug with filtered indices
## Describe the bug
As reported by @PartiallyTyped:
- https://github.com/huggingface/datasets/issues/5111#issuecomment-1278652524

There is an issue with the indices of a filtered dataset.

## Steps to reproduce the bug
```python
ds = Dataset.from_dict({"num": [0, 1, 2, 3]})
ds = ds.filter(lambda num: num % 2 == 0, input_columns="num", batch_size=2)
assert all(item["num"] % 2 == 0 for item in ds)
```

## Expected results
The indices of the filtered dataset should correspond to the examples with "language" equals to "english".

## Actual results
Indices to items with other languages are included in the filtered dataset indices

## Preliminar investigation
It seems a bug introduced by:
- #5030

### PR DESCRIPTION
**Pull request by albertvillanova**
This PR fixes a bug introduced by:
- #5030

Fix #5112.

### CODE REVIEW

**Comment by albertvillanova** [comment]
I think a patch release will be necessary.

**Comment by lhoestq** [comment]
I'm also fixing https://github.com/huggingface/datasets/issues/5111 which will lalso require a patch release

**Review by lhoestq — APPROVED** [review]
Good catch thank you !

**Comment by pepeillo21** [comment]
Hola.convierte la voz a español.gracias

**Comment by pepeillo21** [comment]
O mejor dicho clona la voz en español? Porque me lo traduce en habla inglesa.gracias

**Pull request merged**
