### PR TITLE
Adapt image datasets

### PR DESCRIPTION
**Pull request by mariosasko**
This PR:
* adapts the ImageClassification template to use the new Image feature
* adapts the following datasets to use the new Image feature:
  * beans (+ fixes streaming)
  * cast_vs_dogs (+ fixes streaming)
  * cifar10
  * cifar100
  * fashion_mnist
  * mnist
  * head_qa

cc @nateraw

### CODE REVIEW

**Comment by mariosasko** [comment]
This PR can be merged after #3163 is merged (currently this PR is pretty big because I'm working on the forked branch).

@lhoestq @albertvillanova Could you please take a look at the changes in `src/datasets/utils/streaming_download_manager.py`. These changes were required to support streaming of the `cats_vs_dogs` and the `beans` datasets.

**Comment by mariosasko** [comment]
The CI failures are due to the missing fields in the README files.

**Review by lhoestq — APPROVED** [review]
Looks all good to me ! feel free to merge if it's good on your side

**Comment by lhoestq** [comment]
and thanks for adding support for Path.name and Path.parent for streaming :)

**Pull request merged**
