### PR TITLE
fixed one instance of 'train' to 'test'

### PR DESCRIPTION
**Pull request by alexwdong**
I believe this should be 'test' instead of 'train'

### CODE REVIEW

**Review by albertvillanova — APPROVED** [review]
Hi @alexwdong.

Thanks for reporting. Yes, you are right: it should be `test`.

**Comment by lhoestq** [comment]
Thanks ! good catch

Could you also update the metadata of this dataset ?
You can do so by running
```
datasets-cli test ./datasets/newsgroup --all_configs --save_infos --ignore_verifications
```
This should update the dataset_infos.json file that contains the size of all the splits for example.

**Comment by alexwdong** [comment]
Hi,
`dataset_infos.json` should be updated now.

**Review by lhoestq — APPROVED** [review]
thank you :)

**Pull request merged**
