### PR TITLE
Unpin hfh

### PR DESCRIPTION
**Pull request by lhoestq**
Needed to use those in dataset-viewer:

- dev version of hfh https://github.com/huggingface/dataset-viewer/pull/2781: don't span the hub with /paths-info requests
- dev version of datasets at https://github.com/huggingface/datasets/pull/6875: don't write too big logs in the viewer

close https://github.com/huggingface/datasets/issues/6863

### CODE REVIEW

**Review by severo — APPROVED** [review]

**Review by albertvillanova — COMMENTED** [review]
As I explain in the corresponding issue that I self-assigned (#6863), I was planning to unpin the upper bound of huggingface-hub < 0.23.0 only when the huggingface/transformers#30618 fix is merged and released in a new transformers version, other wise it breaks our CI. The fix has been merged but not released yet.

Also note that datasets-2.19.1 (version currently installed in the dataset-viewer) does not include the pin in huggingface-hub: 
https://github.com/huggingface/datasets/blob/2.19.1/setup.py#L138
https://github.com/huggingface/datasets/blob/bb2664cf540d5ce4b066365e7c8b26e7f1ca4743/setup.py#L138

**Comment by lhoestq** [comment]
transformers 4.40.2 was release yesterday but not sure if it contains the fix

**Comment by albertvillanova** [comment]
> If we urgently need some dev feature for dataset-viewer, I would suggest pushing the feature (cherry-picked) to a dedicated branch with 2.19.1 as its starting point (without opening a PR), and install datasets from that branch.

I have done so:
- Created a branch from 2.19.1: https://github.com/huggingface/datasets/tree/datasets-2.19.1-hotfix
- Cherry-picked the commit in this PR: https://github.com/huggingface/datasets/commit/3638183e2f7e0dce8924e46e7cc21bf6d5d7adfb
- Opened a PR in dataset-viewer to update datasets to this revision: https://github.com/huggingface/dataset-viewer/pull/2783

**Comment by lhoestq** [comment]
hfh 0.23.1 and transformers 4.41.0 as are out out, let's unpin no ?

**Comment by albertvillanova** [comment]
I have re-run the CI to check that is green before.

**Review by albertvillanova — COMMENTED** [review]
The CI is red.

**Comment by lhoestq** [comment]
The errors were coming from `transformers` having FutureWarning when loading models or tokenizers. I disabled the warnings for the `transformers`-related calls since they're not related to `datasets`

**Review by albertvillanova — COMMENTED** [review]
Thanks for the investigation.

Do you know why a `FutureWarning` was transformed into an `OSError`? These are the raised errors:
```
FAILED tests/test_metric_common.py::LocalMetricTest::test_load_metric_bertscore - OSError: Can't load the configuration of 'roberta-large'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'roberta-large' is the correct path to a directory containing a config.json file
FAILED tests/test_fingerprint.py::TokenizersHashTest::test_hash_tokenizer - OSError: Can't load the configuration of 'bert-base-uncased'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'bert-base-uncased' is the correct path to a directory containing a config.json file
```

**Comment by albertvillanova** [comment]
I opened an issue in transformers:
- https://github.com/huggingface/transformers/issues/31002

**Comment by lhoestq** [comment]
It's because the error from the FutureWarning happened when running `cache_file()` from `transformers`, which has some code that try/except and re-raise an OSError

**Review by albertvillanova — COMMENTED** [review]
The error is raised because of our pytest settings: https://github.com/huggingface/datasets/blob/b12a2c5016499cc1d110798c6815f0245f61010e/pyproject.toml#L17-L20

I find contradictory both having this setting (that transforms huggingface-hub FutureWarnings into errors) and at the same time ignoring their warnings that you implemented in https://github.com/huggingface/datasets/pull/6876/commits/889a48d336b866bc3fd1a9c4f1486acaa6758bf3

CC: @Wauplin, who introduced the pytest settings:
- #5623

**Comment by lhoestq** [comment]
alright I disabled the errors on FutureWarning, do you see anything else @albertvillanova or we can merge ?

**Review by albertvillanova — APPROVED** [review]
Thanks. It is good from my side.

**Pull request merged**
