### PR TITLE
Fix docs custom stable version

### PR DESCRIPTION
**Pull request by albertvillanova**
Currently docs default version is 1.5.0. This PR fixes this and sets the latest version instead.

### CODE REVIEW

**Comment by albertvillanova** [comment]
I see that @lhoestq overlooked this PR with his commit 07e2b05. 😢 

I'm adding a script so that this issue does not happen again.

**Comment by lhoestq** [comment]
I think we just need to clarify the release process in setup.py instead of adding a script that does the replacement

**Comment by albertvillanova** [comment]
@lhoestq I really think we should implement a script that performs the release (instead of doing it manually as it is done now), as it is already the case in `transformers`. I will do it in a next PR.

For the moment, this PR includes one of the steps of the release script.

**Review by lhoestq — APPROVED** [review]
Let's automate this then :)

**Pull request merged**
