### PR TITLE
Feature/fidelity metrics from emnlp2020 evaluating and characterizing human rationales

### PR DESCRIPTION
**Pull request by rathoreanirudh**
This metric computes fidelity (Yu et al. 2019, DeYoung et al. 2019) and normalized fidelity (Carton et al. 2020).

### CODE REVIEW

**Comment by lhoestq** [comment]
Hi ! This looks interesting, thanks for adding it :) 

For metrics there should only be two features fields: references and predictions.
Both of them can be defined as you want using nested structures if you need to.
Also I'm not sure what goes into references and what goes into predictions, could you give more details please ?
All the other computations parameters (model etc.) are fine though. Maybe explain a bit more what they're used for

**Comment by rathoreanirudh** [comment]
> Hi ! This looks interesting, thanks for adding it :)
> 
> For metrics there should only be two features fields: references and predictions.
> Both of them can be defined as you want using nested structures if you need to.
> Also I'm not sure what goes into references and what goes into predictions, could you give more details please ?
> All the other computations parameters (model etc.) are fine though. Maybe explain a bit more what they're used for

The `predictions` are the predicted labels by a model for a particular input. Do you mean making `prob_y_hat`, `prob_y_hat_alpha` and the `null_difference` a part of references? Also, I have added the description for other parameters in kwargs_description. I can expand it if that makes sense?

**Comment by lhoestq** [comment]
I think every value that is generated by the model (so label, prob_y_hat, prob_y_hat_alpha etc.) should be in `predictions`.
Feel free to add more details in the kwargs_description, this is very useful for the end user.

**Comment by rathoreanirudh** [comment]
Hi @lhoestq , I have updated the code according to your feedback. Please, let me know if it looks good and can be merged now.

**Comment by albertvillanova** [comment]
Metrics are deprecated in `datasets` and `evaluate` should be used instead: https://github.com/huggingface/evaluate

**Pull request closed without merging**
