### PR TITLE
Ensure last tqdm update in `map`

### PR DESCRIPTION
**Pull request by mariosasko**
This PR modifies `map` to:
* ensure the TQDM bar gets the last progress update
* when a map function fails, avoid throwing a chained exception in the single-proc mode

### CODE REVIEW

**Review by lhoestq — APPROVED** [review]
thanks !

**Comment by lhoestq** [comment]
I just tried on colab and it didn't finish the progress bar for some reason.

Maybe we need to call `pbar.close()` before `return`

**Comment by lhoestq** [comment]
(just added .close() - let me try quickly if it works now)

**Comment by lhoestq** [comment]
it worked ! :)

image

**Review by lhoestq — APPROVED** [review]

**Comment by mariosasko** [comment]
(the BadZipFile error is unrelated to the changes)

**Pull request merged**
