### PR TITLE
Audio datacard update - first pass

### PR DESCRIPTION
**Pull request by meg-huggingface**
Filling out data card "Personal and Sensitive Information" for speech datasets to note PII concerns

### CODE REVIEW

**Comment by mcmillanmajora** [comment]
I'm not sure that we want to change the tags at the top of the cards by hand. Those are used to create the tags in the hub. Although looking at all the tags now, we might want to normalize the current tags again (hyphens or no, ".0" or no). Maybe we could add a binary tag for public domain or not?

**Comment by meg-huggingface** [comment]
> 

That's a good point, I didn't realize these were auto-populated.
At the same time, some of them are wrong -- how/where are they auto-populated?  Seems like we should fix it at that source for the future.
In the mean time, I see that "cc0-1.0" is the desired tag for public domain, so I will change that for now.

**Review by patrickvonplaten — APPROVED** [review]
Thanks a lot @meg-huggingface

**Review by lhoestq — APPROVED** [review]
Thanks !

**Pull request merged**
