### PR TITLE
Fix infinite loop in WindowsFileLock

### PR DESCRIPTION
**Pull request by albertvillanova**
Raise exception to avoid infinite loop.

### CODE REVIEW

**Comment by lhoestq** [comment]
How is it possible to get an infinite loop ? Can you add more details ?

**Comment by albertvillanova** [comment]
Yes, in Windows, if the filename is too long, a `FileNotFoundError` is raised. The exception should be raised in this case.

If other process has the file locked, then `PermissionError` is raised. In this case, `pass` is OK.

**Comment by lhoestq** [comment]
Note that the filelock module comes from this project that hasn't changed in years - while still being used by ten of thousands of projects:
https://github.com/benediktschmitt/py-filelock

Unless we have proper tests for this, I wouldn't recommend to change it

**Comment by lhoestq** [comment]
I'm pretty sure many things from the library could break for windows users that haven't disabled the max path length limit.
Maybe it would be simpler to simply raise an error on startup. For exampe, for windows users the error could ask them to disable the limit if it's not been disabled yet ?

**Pull request closed without merging**
