### PR TITLE
Update cats_vs_dogs size

### PR DESCRIPTION
**Pull request by mariosasko**
It seems like 12 new examples have been added to the `cats_vs_dogs`. This PR updates the size in the card and the info file to avoid a verification error (reported by @stevhliu).

### CODE REVIEW

**Review by lhoestq — APPROVED** [review]
Thanks !

**Comment by lhoestq** [comment]
Maybe `NonMatchingSplitsSizesError` errors should also tell the user to try using a more recent version of the dataset to get the fixes ?

**Comment by mariosasko** [comment]
@lhoestq Good idea. Will open a new PR to improve the error messages of NonMatchingSplitsSizesError, NonMatchingChecksumsError, ...

**Comment by murphyk** [comment]
It seems there is still a problem. I am using datasets version 2.5.1. 
I just typed `ds = load_dataset("cats_vs_dogs")` and get the error below.

```
NonMatchingSplitsSizesError: [{'expected': SplitInfo(name='train', num_bytes=3893603, num_examples=23422, dataset_name='cats_vs_dogs'), 'recorded': SplitInfo(name='train', num_bytes=3891612, num_examples=23410, dataset_name='cats_vs_dogs')}]
```
It looks like the dataset still only has 23,410 examples....

**Comment by lhoestq** [comment]
Thanks for reporting, I opened https://github.com/huggingface/datasets/pull/5047

**Pull request merged**
