### PR TITLE
Add Wiki Lingua Dataset

### PR DESCRIPTION
**Pull request by katnoria**
Hello,

This is my first PR. 

I have added Wiki Lingua Dataset along with dataset card to the best of my knowledge.
There was one hiccup though. I was unable to create dummy data because the data is in pkl format.
From the document, I see that:
```At the moment it supports data files in the following format: txt, csv, tsv, jsonl, json, xml```

### CODE REVIEW

**Comment by katnoria** [comment]
I am done adding the dataset. Requesting to review and advise.

**Comment by lhoestq** [comment]
looks like this PR has changes about many other files than the ones for WIki Lingua 

Can you create another branch and another PR please ?

**Comment by lhoestq** [comment]
Any reason to have english as the default config over the other languages ?

**Comment by katnoria** [comment]
> looks like this PR has changes about many other files than the ones for WIki Lingua
> 
> Can you create another branch and another PR please ?

Ok, I will create another branch and submit a fresh PR.

**Comment by katnoria** [comment]
> Any reason to have english as the default config over the other languages ?

The data for all other languages has a direct reference to English equivalent sentence. Thus, I kept English as default.

**Comment by lhoestq** [comment]
closing in favor of #1470

**Pull request closed without merging**
