### PR TITLE
Fix incorrect MRQA train+SQuAD URL

### PR DESCRIPTION
**Pull request by jimmycode**
Fix issue #1115

### CODE REVIEW

**Comment by lhoestq** [comment]
Thanks ! could you regenerate the dataset_infos.json file ?

```
datasets-cli test ./datasets/mrqa --save_infos --all_configs --ignore_verifications
```

also cc @VictorSanh

**Comment by VictorSanh** [comment]
Oooops, good catch @jimmycode

**Comment by jimmycode** [comment]
> Thanks ! could you regenerate the dataset_infos.json file ?
> 
> ```
> datasets-cli test ./datasets/mrqa --save_infos --all_configs --ignore_verifications
> ```
> 
> also cc @VictorSanh

Updated the `dataset_infos.json` file.

**Review by lhoestq — APPROVED** [review]
thanks !

**Pull request merged**
