### PR TITLE
Complete the mlqa dataset card

### PR DESCRIPTION
**Pull request by eldhoittangeorge**
I fixed the issue #4808 

Details of PR:
- Added languages included in the dataset. 
- Added task id and task category. 
- Updated the citation information.

### CODE REVIEW

**Review by albertvillanova — CHANGES_REQUESTED** [review]
Thanks for your contribution, @eldhoittangeorge. 

The CI error message: https://github.com/huggingface/datasets/runs/7743526624?check_suite_focus=true
```
E           ValueError: The following issues have been found in the dataset cards:
E           YAML tags:
E           __init__() missing 5 required positional arguments: 'annotations_creators', 'language_creators', 'license', 'size_categories', and 'source_datasets'
```

**Comment by eldhoittangeorge** [comment]
> Thanks for your contribution, @eldhoittangeorge.
> 
> The CI error message: https://github.com/huggingface/datasets/runs/7743526624?check_suite_focus=true
> 
> ```
> E           ValueError: The following issues have been found in the dataset cards:
> E           YAML tags:
> E           __init__() missing 5 required positional arguments: 'annotations_creators', 'language_creators', 'license', 'size_categories', and 'source_datasets'
> ```

I will fix the CI error.

**Comment by albertvillanova** [comment]
@eldhoittangeorge, thanks again for all the fixes. Just a minor one before we can merge this PR: https://github.com/huggingface/datasets/runs/7744885754?check_suite_focus=true
```
E           YAML tags:
E           Could not validate the metadata, found the following errors:
E           * field 'language_creators':
E           	['unknown'] are not registered tags for 'language_creators', reference at https://github.com/huggingface/datasets/tree/main/src/datasets/utils/resources/creators.json
```

**Comment by eldhoittangeorge** [comment]
> 

Thanks, I updated the file. 
A small suggestion can you mention this link https://github.com/huggingface/datasets/tree/main/src/datasets/utils/resources/  in the contribution page. So that others will know the acceptable values for the tags.

**Review by albertvillanova — COMMENTED** [review]
Thank you. In our docs [Create a dataset card](https://huggingface.co/docs/datasets/dataset_card), we suggest using the Datasets Tagging application: https://huggingface.co/spaces/huggingface/datasets-tagging

**Review by albertvillanova — APPROVED** [review]
Thanks for the completion of the dataset card.

**Pull request merged**
