### PR TITLE
Add personaldialog datasets

### PR DESCRIPTION
**Pull request by silverriver**
It seems that all tests are passed

### CODE REVIEW

**Comment by silverriver** [comment]
I only made a trivial modification in my commit https://github.com/huggingface/datasets/pull/4431/commits/402c893d35224d7828176717233909ac5f1e7b3e

I have submitted a PR #4434 for the about issue.

**Review by lhoestq — COMMENTED** [review]
Awesome thanks for adding this dataset :)

I just have one comment about the licensing.

Also it seems that you already have the dataset in https://huggingface.co/datasets/silver/personal_dialog, so it's unnecessary to add it here

**Comment by silverriver** [comment]
> Awesome thanks for adding this dataset :)
> 
> I just have one comment about the licensing.
> 
> Also it seems that you already have the dataset in https://huggingface.co/datasets/silver/personal_dialog, so it's unnecessary to add it here

Thank you very much for your comment.

So, should I close this PR?

**Comment by lhoestq** [comment]
Thanks for fixing the licensing section :)

> So, should I close this PR?

Yes you can close this PR, it's better if your dataset is under your namespace at https://huggingface.co/datasets/silver/personal_dialog :)

Don't forget to update the licensing section on https://huggingface.co/datasets/silver/personal_dialog as well

**Pull request closed without merging**
