### PR TITLE
[Timit_asr] Make sure not only the first sample is used 

### PR DESCRIPTION
**Pull request by patrickvonplaten**
When playing around with timit I noticed that only the first sample is used for all indices. I corrected this typo so that the dataset is correctly loaded.

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
cc @lhoestq  @vrindaprabhu

**Comment by patrickvonplaten** [comment]
Failing `run (push)` is unrelated -> merging

**Comment by elgeish** [comment]
Thanks for fixing this, it was affecting my runs for https://github.com/huggingface/transformers/pull/10581/

**Comment by vrindaprabhu** [comment]
I am seeing this very late! Sorry for the blunder everyone! :(

**Pull request merged**
