### PR TITLE
Fix backward compatibility in Dataset.load_from_disk

### PR DESCRIPTION
**Pull request by albertvillanova**
Fix backward compatibility when loading from disk an old dataset saved to disk with indices using key "_indices_data_files".

Related to #2195.

### CODE REVIEW

**Comment by albertvillanova** [comment]
Hi @lhoestq, could you please check if this makes sense? Thanks.

**Review by lhoestq — APPROVED** [review]
Good catch !!

**Comment by lhoestq** [comment]
What about using `_indices_data_files` field in save_to_diskinstead of `_indices_files` ?
This way future datasets can also be reloaded from older versions of the lib

**Comment by albertvillanova** [comment]
Yes, I have seen it is not released yet...

You are right! It was your awesome PR on Tables which renamed this. If there is no particular reason for this renaming, yes, we could switch it back to the previous `_indices_data_files`. ;)

**Pull request merged**
