### PR TITLE
Add collection3 dataset

### PR DESCRIPTION
**Pull request by pefimov**

### CODE REVIEW

**Comment by albertvillanova** [comment]
Hi @pefimov. Thanks for you awesome work on this dataset contribution.

However, now we are using the Hub to add new datasets, instead of this GitHub repo. 

You could share this dataset under the appropriate Hub organization namespace. This way the dataset will be accessible using:
```python
ds = load_dataset("<org_namespace>/collection3")
```

You have the procedure documented in our online docs: 
- [Create a dataset loading script](https://huggingface.co/docs/datasets/dataset_script)
- [Share](https://huggingface.co/docs/datasets/share)

Moreover, datasets shared on the Hub no longer need the dummy data files.

Please, feel free to ping me if you need any further guidance/support.

**Review by albertvillanova — COMMENTED** [review]
Requested to be moved tot he Hub.

**Comment by pefimov** [comment]
> However, now we are using the Hub to add new datasets, instead of this GitHub repo.
> 
> You could share this dataset under the appropriate Hub organization namespace. This way the dataset will be accessible using:
> 
> ```python
> ds = load_dataset("<org_namespace>/collection3")
> ```
> 
Hi @albertvillanova . Thank you for your response.

I thought that Collection3 is large and important dataset in Russian presented in 2016 but not presented in huggingface.

Also I am not related to authors or organisation of dataset

**Comment by albertvillanova** [comment]
The current policy of sharing datasets on the Hub instead of in this GitHub repo has no relation with the importance of the dataset: https://huggingface.co/docs/datasets/share#datasets-on-github-legacy 
> The distinction between a Hub dataset and a dataset from GitHub only comes from the legacy sharing workflow. It does not involve any ranking, decisioning, or opinion regarding the contents of the dataset itself.

It is not required to be an author/owner (or belong to the organization that is owner) of the dataset in order to share it on the Hub (as it was not the case when sharing them on this GitHub repo). 

It is recommended to share it under an organization namespace that makes sense though. For this specific dataset, do you know of a clear organization under which it could be shared on the Hub? Maybe "labinform", or "Information Research Laboratory" or "Lomonosov Moscow State University"?

In cases like this, where the org is not evident, one possibility could be to contact the dataset owners/creators and ask them. According the publication paper, the authors are:
- V.A. Mozharova
- N.V. Loukachevitch
I think maybe it would be worth contacting them.

**Comment by albertvillanova** [comment]
@pefimov I have contacted the authors (and put you in CC).

**Comment by albertvillanova** [comment]
Reply from the authors:
> It is better to use name: Research Computing Center of Lomonosov Moscow State University (short name RCC-MSU)
> https://rcc.msu.ru/en

**Comment by pefimov** [comment]
Thanks

**Pull request closed without merging**
