### PR TITLE
add taskmaster3

### PR DESCRIPTION
**Pull request by patil-suraj**
Adding Taskmaster-3 dataset
https://github.com/google-research-datasets/Taskmaster/tree/master/TM-3-2020.

The dataset structure almost same as original dataset with these two changes

1. In original dataset, each `apis` has a `args` filed which is a `dict`  with variable keys, which represent the name and value of the args. Here converted that to a `list` of `dict` with keys `arg_name` and `arg_value`. For ex.

```python
args = {"name.movie": "Mulan", "name.theater": ": "Mountain AMC 16"}
```
becomes 
```python
[
  {
    "arg_name": "name.movie",
    "arg_value": "Mulan"
  },
  {
    "arg_name": "name.theater",
    "arg_value": "Mountain AMC 16"
  }
]
```

2. Each `apis` has a `response` which is also a `dict` with variable keys representing response name/type and it's value. As above converted it to `list` of `dict` with keys `response_name` and `response_value`.

### CODE REVIEW

**Review by lhoestq — COMMENTED** [review]
Really cool thanks !

Can you try to reduce the size of the dummy data ?
To do so feel free to take a look inside the dummy_data.zip and for the files from data_01.json to data.19.json you can just replace the data with an empty list `[]`. Therefore only the data_00.json will contain examples and it should be fine.

**Comment by lhoestq** [comment]
(you were unlucky, my rule of thumb for reducing the dummy data is to check whether they're above 50KB and you're at 52KB ^^')

**Comment by patil-suraj** [comment]
> (you were unlucky, my rule of thumb for reducing the dummy data is to check whether they're above 50KB and you're at 52KB ^^')

Oops :(

Thanks for the suggestion, will reduce the size

**Review by lhoestq — APPROVED** [review]
Nice thanks !

**Pull request merged**
