### PR TITLE
dataset(ncslgr): add initial loading script

### PR DESCRIPTION
**Pull request by AmitMY**
clean #789

### CODE REVIEW

**Review by lhoestq — COMMENTED** [review]
Hi ! thanks for cleaning the PR :) 

Could you add the tags of the dataset card ? 
It's some yaml that we expect to see at the top of the dataset card (README.md file for this dataset). We require the tags for datasets since this week's sprint
You can find more info here : https://github.com/huggingface/datasets/blob/master/ADD_NEW_DATASET.md#tag-the-dataset-and-write-the-dataset-card

Since it's a new thing, feel free to ping me if you have any question regarding the tags

**Comment by AmitMY** [comment]
@lhoestq I added the README files, and now the tests fail... (check commit history, only changed MD file)
The tests seem a bit unstable

**Comment by lhoestq** [comment]
the `RemoteDatasetTest ` errors in the CI are fixed on master so it's fine

**Review by lhoestq — APPROVED** [review]
Thanks ! all good now :)

**Comment by lhoestq** [comment]
merging since the CI is fixed on master

**Pull request merged**
