### PR TITLE
fix get_metadata_patterns function args error

### PR DESCRIPTION
**Pull request by d710055071**
Bug get_metadata_patterns arg error https://github.com/huggingface/datasets/issues/6517

### CODE REVIEW

**Comment by d710055071** [comment]
#6517

**Review by albertvillanova — APPROVED** [review]
Thanks, good catch!

**Comment by d710055071** [comment]
hello!
@albertvillanova  
Thank you very much for your recognition。
When can this PR be merged?

**Review by lhoestq — APPROVED** [review]
Good catch !

**Pull request merged**
