### PR TITLE
Common voice validated partition

### PR DESCRIPTION
**Pull request by shalymin-amzn**
This patch adds access to the 'validated' partitions of CommonVoice datasets (provided by the dataset creators but not available in the HuggingFace interface yet).
As 'validated' contains significantly more data than 'train' (although it contains both test and validation, so one needs to be careful there), it can be useful to train better models where no strict comparison with the previous work is intended.

### CODE REVIEW

**Comment by shalymin-amzn** [comment]
Hi @patrickvonplaten - could you please advise whether this would be a welcomed change, and if so, who I consult regarding the unit-tests?

**Comment by patrickvonplaten** [comment]
I'd be happy with adding this change. @anton-l @lhoestq - what do you think?

**Comment by shalymin-amzn** [comment]
Thanks! I think that there are 2 cases for using the validated partition: 1) trainset = {validated - dev - test}, dev and test as they come; 2) train, dev, and test sampled from validated manually with the desired ratios.
In either case, I think that it's quite a big change on the HF interface part, so could as well be taken care of in the client code. Or is it not? (In which case, what's the most compact way to implement this?)

**Comment by lhoestq** [comment]
What's important IMO is to let the users as much flexibility as they need - so we try to not do too much regarding splits to not constrain users. So I guess the way it is right now is ok. Can you confirm that it's ok @patrickvonplaten and that it won't break some speech training script out there ?

**Comment by anton-l** [comment]
@lhoestq all split names are explicit in our example scripts, so this shouldn't break anything, feel free to merge :)
I'll go ahead and add this to the official `mozilla-foundation` datasets as well

**Comment by patrickvonplaten** [comment]
Good for me! This has no down-sides whatoever IMO

**Review by lhoestq — APPROVED** [review]
Great ! Thanks everyone :)

**Pull request merged**
