### PR TITLE
Bump max range of dill to 0.3.8

### PR DESCRIPTION
**Pull request by ringohoffman**
Release on Jan 27, 2024: https://pypi.org/project/dill/0.3.8/#history

### CODE REVIEW

**Comment by ringohoffman** [comment]
Hmm these errors look pretty weird... can they be retried?

**Comment by mariosasko** [comment]
Hi, thanks for working on this! To fix the errors, you also need to update [this file](https://github.com/huggingface/datasets/blob/main/src/datasets/utils/_dill.py) (by adding `version.parse("0.3.8").release` to the lists)

**Review by mariosasko — APPROVED** [review]
Thanks!

**Review by albertvillanova — APPROVED** [review]
Thank you.

**Pull request merged**
