### PR TITLE
Make numpy arrow extractor faster

### PR DESCRIPTION
**Pull request by lhoestq**
I changed the NumpyArrowExtractor to call directly to_numpy and see if it can lead to speed-ups as discussed in https://github.com/huggingface/datasets/issues/2498

This could make the numpy/torch/tf/jax formatting faster

### CODE REVIEW

**Comment by lhoestq** [comment]
Looks like we have a nice speed up in some benchmarks. For example:
- `read_formatted numpy 5000`:  4.584777 sec -> 0.487113 sec
- `read_formatted torch 5000`:  4.565676 sec -> 1.289514 sec

**Comment by vblagoje** [comment]
Can we convert this draft to PR @lhoestq ?

**Comment by lhoestq** [comment]
Ready for review ! cc @vblagoje

**Comment by vblagoje** [comment]
@lhoestq I tried the branch and it works for me. Although performance trace now shows a speedup, the overall pre-training speed up is minimal. But that's on my plate to explore further.

**Comment by lhoestq** [comment]
Thanks for investigating @vblagoje 

@albertvillanova , do you have any comments on this PR ? Otherwise I think we can merge it

**Pull request merged**
