### PR TITLE
Add machine translated multilingual STS benchmark dataset

### PR DESCRIPTION
**Pull request by PhilipMay**
also see here https://github.com/PhilipMay/stsb-multi-mt

### CODE REVIEW

**Comment by PhilipMay** [comment]
Hello dear maintainer, are there any comments or questions about this PR?

**Review by lhoestq — COMMENTED** [review]
Really cool thank you :)

The dataset script looks all good ! Good job.
The dummy data and the dataset_infos.json are also perfect :)

For the readme, can you follow the template for the README.md ? You can find the template here:
https://github.com/huggingface/datasets/tree/master/templates

Ideally it would be cool to fill the info for those sections at least:
- Dataset Summary
- Languages
- Data Instances
- Data Fields
- Data Splits

Let me know if you have questions about this !

**Comment by PhilipMay** [comment]
@iamollas thanks for the feedback. I did not see the template.
I improved it...

**Comment by PhilipMay** [comment]
Should be clean for merge IMO.

**Review by lhoestq — APPROVED** [review]
Thank you !
I just added the table of contents and the missing sections in the dataset card :)

**Comment by PhilipMay** [comment]
@lhoestq CI is green. ;-)

**Comment by lhoestq** [comment]
Thanks again ! this is awesome :)

**Comment by PhilipMay** [comment]
Thanks for merging. :-)

**Pull request merged**
