### PR TITLE
adding hind_encorp dataset

### PR DESCRIPTION
**Pull request by rahul-art**
adding Hindi_Encorp05 dataset

### CODE REVIEW

**Comment by rahul-art** [comment]
help needed in dummy data

**Comment by rahul-art** [comment]
extension of the file is .plaintext so dummy data generation is failing

**Comment by lhoestq** [comment]
you can add the `--match_text_file "*.plaintext"` flag when generating the dummy data

also it looks like the PR is empty, is this expected ?

**Comment by rahul-art** [comment]
yes it is expected because I  made all my changes in  PR  #1186  then I again run code and open PR #1188 to see if this time test passes or not only so there is no code change from #1186 to #1188  
i tried  --match_text_file "*.plaintext" this time it is also not generating dummy data don't know why

**Comment by lhoestq** [comment]
well this PR includes no code change at all, can you make sure you added your changes in this one ?

**Comment by lhoestq** [comment]
feel free to ping me when you have added the files so I can take a look and help you with the dummy data

**Comment by rahul-art** [comment]
how to do that i dont know did i have to open new PR

**Comment by rahul-art** [comment]
actually all my changes are visible in  #1186 but  don't know how to show same changes here

**Comment by rahul-art** [comment]
these are a the which i did in #1186 and same in #1188 












these same codes are in both #1186 and #1188 so because it is already present from PR #1186 because of that it is showing zeor code change in #1188 because it is already present from #1186 how i can show or highlight those changes

**Comment by lhoestq** [comment]
well for me https://github.com/huggingface/datasets/pull/1188/files is blank

**Comment by lhoestq** [comment]
This PR tries to merge the master branch of you fork into this repo, however I can't find changes with your files inside your master branch.

Maybe you can fork again the repo and try to create another PR ?

**Comment by rahul-art** [comment]
@lhoestq  i  opened a new pr #1438 but this time it fails many circl ci tests

**Comment by lhoestq** [comment]
Closing this one since a new PR was created

**Pull request closed without merging**
