### PR TITLE
Add ChrEn

### PR DESCRIPTION
**Pull request by yjernite**
Adding the Cherokee English machine translation dataset of https://github.com/ZhangShiyue/ChrEn

### CODE REVIEW

**Review by lhoestq — COMMENTED** [review]
Feel free to add `xlrd` in setup.py under `TESTS_REQUIRE` :)

**Comment by lhoestq** [comment]
I just saw your PR actually ^^

**Comment by yjernite** [comment]
> I just saw your PR actually ^^

Somehow that still doesn't work, lmk if you have any ideas.

**Comment by lhoestq** [comment]
Did you rebase from master ?

**Pull request merged**
