### PR TITLE
Add `fn_kwargs` param to `IterableDataset.map`

### PR DESCRIPTION
**Pull request by mariosasko**
Add the `fn_kwargs` parameter to `IterableDataset.map`.

("Resolves" https://discuss.huggingface.co/t/how-to-use-large-image-text-datasets-in-hugging-face-hub-without-downloading-for-free/22780/3)

### CODE REVIEW

**Review by lhoestq — APPROVED** [review]
LGTM !

**Comment by brianhill11** [comment]
Thank you for adding this fix! 

Would it be possible to get `fn_kwargs` added to `IterableDatasetDict.map` as well? It looks like a very similar problem, and hopefully shouldn't be a huge change.

**Comment by mariosasko** [comment]
Hi @brianhill11! https://github.com/huggingface/datasets/pull/5810 adds this (opened a couple of days ago). It should be merged soon.

**Comment by brianhill11** [comment]
That's fantastic news, thanks @mariosasko ! I'll give it a shot once the changes are merged in.

**Pull request merged**
