### PR TITLE
Add CaSiNo dataset

### PR DESCRIPTION
**Pull request by kushalchawla**
Hi. I request you to add our dataset to the repository. 

This data was recently published at NAACL 2021: https://aclanthology.org/2021.naacl-main.254.pdf

### CODE REVIEW

**Comment by kushalchawla** [comment]
Hi @lhoestq  

Just a request to look at the dataset. Please let me know if any changes are necessary before merging it into the repo. Thank you.

**Review by lhoestq — APPROVED** [review]
Nice ! Thanks for adding this dataset

Good job with the dataset card and the dataset script :)
LGTM !

**Comment by kushalchawla** [comment]
Hey @lhoestq 

Thanks for merging it. One question: I still cannot find the dataset on https://huggingface.co/datasets. Does it take some time or did I miss something?

**Comment by lhoestq** [comment]
Hi ! It takes a few hours or a day for the list of datasets on the website to be updated ;)

**Pull request merged**
