### PR TITLE
Fix bug with labels of eurlex config of lex_glue dataset

### PR DESCRIPTION
**Pull request by iliaschalkidis**
Fix for a critical bug in the EURLEX dataset label list to make LexGLUE EURLEX results replicable. 

In LexGLUE (Chalkidis et al., 2022), the following is mentioned w.r.t. EUR-LEX: _"It supports four different label granularities, comprising 21, 127, 567, 7390 EuroVoc concepts, respectively. We use the 100 most frequent concepts from level 2 [...]”._ The current label list has all 127 labels, which leads to different (lower) results, as communicated by users.

Thanks!

### CODE REVIEW

**Comment by iliaschalkidis** [comment]
@JamesLYC88 here is the fix! Thanks again!

**Review by albertvillanova — APPROVED** [review]
Thanks for the fix, @iliaschalkidis.

**Comment by iliaschalkidis** [comment]
Thanks, @albertvillanova. When do you expect that this change will take effect when someone downloads the dataset?

**Comment by albertvillanova** [comment]
The change is immediately available now.

**Pull request merged**
