### PR TITLE
add MSE and MAE metrics - V2

### PR DESCRIPTION
**Pull request by dnaveenr**
Created a new pull request to resolve unrelated changes in PR caused due to rebasing.
Ref Older PR :  [#3845](https://github.com/huggingface/datasets/pull/3845) 

Feature request here : Add support for continuous metrics (RMSE, MAE) [#3608](https://github.com/huggingface/datasets/issues/3608)

### CODE REVIEW

**Comment by dnaveenr** [comment]
@mariosasko New PR here. I'm not sure how to add you as a co-author here.  Also I see flake8 tests are failing, any inputs on how to resolve this ?
Also, let me know if any other changes are required. Thank you.

**Comment by dnaveenr** [comment]
Great. Thank you.

**Review by lhoestq — APPROVED** [review]
Thanks ! It looks all good :)

**Comment by ck37** [comment]
Thanks so much for this 🙏 💯

**Pull request merged**
