### PR TITLE
Add FreebaseQA dataset

### PR DESCRIPTION
**Pull request by gchhablani**
Adding FreebaseQA dataset suggested in PR #1435 with minor edits. Also closes that PR.
Requesting @lhoestq to review.

### CODE REVIEW

**Comment by lhoestq** [comment]
Hi ! It looks like this PR contains changes about other datasets than freebase_qa such as DuoRC.

Can you remove these changes please ?

**Review by lhoestq — COMMENTED** [review]
Really cool thanks :)
This looks all good to me.
Once the changes about other datasets (duorc, gem) are removed from this PR we cam merge

**Comment by gchhablani** [comment]
Hi @lhoestq,

I'm unsure why that happened, I'm unable to remove the duorc commit from the branch.  Any help?

**Comment by lhoestq** [comment]
Hi @gchhablani 
I think you can simply create another branch and another PR.

If I understand correctly the github diff is messed up because you rebased instead of merge.
Rebasing is supposed to be used only before pushing the branch the first time, or github messes up the diff.
If you want to include changes from master on a branch that is already push you need to use git merge.

**Comment by gchhablani** [comment]
Thanks @lhoestq.

I understand the issue now. Sorry for bothering you unnecessarily, I'm pretty new to contributing on GitHub.

**Comment by lhoestq** [comment]
No problem, I'm not a big fan of this weird behavior tbh.
Thanks for making a new PR

**Comment by gchhablani** [comment]
@lhoestq Haha, well, it's not as weird as not reading the [instructions](https://github.com/huggingface/datasets/blob/master/ADD_NEW_DATASET.md#open-a-pull-request-on-the-main-huggingface-repo-and-share-your-work).
Also, I'm enjoying adding new datasets so it's all cool :)

**Pull request closed without merging**
