### PR TITLE
Remove unused py_utils objects

### PR DESCRIPTION
**Pull request by albertvillanova**
Remove unused/unnecessary py_utils functions/classes.

### CODE REVIEW

**Review by lhoestq — APPROVED** [review]
Thanks :)

**Comment by lhoestq** [comment]
Hmmm this one broke master. T'm fixing it.

Maybe because your branch was outdated ?

**Comment by albertvillanova** [comment]
Sorry @lhoestq, I forgot to update the imports... :/

**Comment by lhoestq** [comment]
It's fine, the CI should have caught this tbh. Not sure why it did't fail

**Pull request merged**
