### PR TITLE
Update `_format_columns` in `remove_columns`

### PR DESCRIPTION
**Pull request by alvarobartt**
As explained at #4398, when calling `dataset.add_faiss_index` under certain conditions when calling a sequence of operations `cast_column`, `map`, and `remove_columns`, it fails as it's trying to look for already removed columns.

So on, after testing some possible fixes, it seems that setting the dataset format right after removing the columns seems to be working fine, so I had to add a call to `.set_format` in the `remove_columns` function.

Hope this helps!

### CODE REVIEW

**Comment by alvarobartt** [comment]
🤗 This PR closes https://github.com/huggingface/datasets/issues/4398

**Comment by mariosasko** [comment]
I made a small change to make the fix easier to understand.

**Comment by alvarobartt** [comment]
Hi, @mariosasko thanks! It makes sense, sorry I'm not that familiar with `datasets` code 😩

**Review by albertvillanova — CHANGES_REQUESTED** [review]
Hi @alvarobartt thanks for the fix.

I think this PR would need a regression test, so that we are sure we will not reintroduce the bug in the future. Would you mind to add it?

Feel free to ping me if you need some help.

**Comment by alvarobartt** [comment]
Sure @albertvillanova I'll do that later today and ping you once done, thanks! :hugs:

**Comment by alvarobartt** [comment]
Hi again @albertvillanova! Let me know if those tests are fine 🤗

**Comment by albertvillanova** [comment]
Hi @alvarobartt,

I had to edit edit your file using the GitHub UI in order to force the re-running of CI tests: I don't know why previously, after your last commit, it was not triggered. I did so because I think your tests are failing.

First I tried to do it using my terminal, but I don't have push right to your PR branch: I would ask you next time you open a PR, please mark the checkbox "Allow edits from maintainers": https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

**Comment by alvarobartt** [comment]
Hi @albertvillanova, let me check those again! And regarding that checkbox I thought it was already checked so my bad there 😩

**Comment by albertvillanova** [comment]
@lhoestq any idea why the CI is not triggered?

**Comment by albertvillanova** [comment]
@alvarobartt I have tested locally and the tests continue failing.

I think there is an implementation error: `new_dset._format_columns` is always `None` in those cases.

**Comment by alvarobartt** [comment]
You're right @albertvillanova I was indeed running the tests with `datasets==2.2.0` rather than with the branch version, I'll check it again! Sorry for the inconvenience...

**Comment by alvarobartt** [comment]
> @alvarobartt I have tested locally and the tests continue failing.
> 
> I think there is a basis error: `new_dset._format_columns` is always `None` in those cases.

In order to have some regressions tests for the fixed scenario, I've manually updated the value of `_format_columns` in the `ArrowDataset` so as to check whether it's updated or not right after calling `remove_columns`, and it does behave as expected, so with the latest version of this branch the reported issue doesn't occur anymore.

**Review by alvarobartt — COMMENTED** [review]
🤗 Regressions tests have already been included!

**Review by albertvillanova — CHANGES_REQUESTED** [review]
Thanks.

I would remove the tests assertions: `self.assertEqual(..., None)`.
The regression tests of the fix you implement only apply when `self._format_columns` is not `None`.

What about adding an analogue regression test also in `tests/test_dataset_dict.py`?

**Comment by alvarobartt** [comment]
Hi again @albertvillanova sorry I was on leave! I'll do that ASAP :hugs:

**Comment by alvarobartt** [comment]
@albertvillanova, does it make sense to add regression tests for `DatasetDict`? As `DatasetDict` doesn't have the attribute `_format_columns`, when we call `remove_columns` over a `DatasetDict` it removes the columns and updates the attributes of each split which is an `ArrowDataset`. So on, we can either update first the `_format_columns` attribute of each split and then remove the columns over the `DatasetDict`, or just loop over the splits of `DatasetDict` and remove the columns right after updating `_format_columns` of each `ArrowDataset`.

I assume that the best regression test is the one implemented (mentioned first above), let me know if there's a better way to do that 👍🏻

**Comment by lhoestq** [comment]
I think there's already a decorator to support transmitting the right `_format_columns`: `@transmit_format`, have you tried adding this decorator to `remove_columns` ?

**Comment by alvarobartt** [comment]
> 

I can check now!

**Comment by alvarobartt** [comment]
> I think there's already a decorator to support transmitting the right `_format_columns`: `@transmit_format`, have you tried adding this decorator to `remove_columns` ?

Hi @lhoestq I can check now!

**Comment by alvarobartt** [comment]
It worked indeed @lhoestq, thanks for the proposal and the review! 🤗

**Comment by mariosasko** [comment]
Oops, I forgot about `@transmit_format`'s existence. From what I see, we should also use this decorator in `flatten`, `rename_column` and  `rename_columns`. 

@alvarobartt Let me know if you'd like to work on this (in a subsequent PR).

**Review by lhoestq — APPROVED** [review]
Thanks ! Merging now :)

**Pull request merged**
