### PR TITLE
test v0.12.0.rc0

### PR DESCRIPTION
**Pull request by Wauplin**
DO NOT MERGE.
Only to test the CI.

cc @lhoestq @albertvillanova

### CODE REVIEW

**Comment by albertvillanova** [comment]
@Wauplin I was testing it in a dedicated branch without opening a PR: https://github.com/huggingface/datasets/commits/test-hfh-0.12.0rc0

**Comment by Wauplin** [comment]
Oops, sorry @albertvillanova. I thought for next time I'll start the CIs before pinging everyone.
I'm closing this one.

**Comment by albertvillanova** [comment]
@Wauplin in your Slack message, you asked people from every major dependent library to check that our CI work. That is why I am checking it... :)

**Comment by Wauplin** [comment]
Yes, yes I know. Completely my fault on this one

**Pull request closed without merging**
