### PR TITLE
Perform hidden file check on relative data file path

### LINKED ISSUE #4549: FileNotFoundError when passing a data_file inside a directory starting with double underscores
Bug experienced in the `accelerate` CI: https://github.com/huggingface/accelerate/runs/7016055148?check_suite_focus=true

This is related to https://github.com/huggingface/datasets/pull/4505 and the changes from https://github.com/huggingface/datasets/pull/4412

### PR DESCRIPTION
**Pull request by mariosasko**
Fix #4549

### CODE REVIEW

**Review by lhoestq — APPROVED** [review]
Thanks ! LGTM :)

Though it doesn't fix the issue if the relative path points to an actual file (not a pattern) and if it contains a double underscores (so it doesn't completely "Fix https://github.com/huggingface/datasets/issues/4549"):

```python
resolve_patterns_locally_or_by_urls(
    base_path="/Users/quentinlhoest/Desktop/hf/datasets/playground",
    patterns=[".yo/data.txt"]
)
```

^ this one should return the file

but we still have to make sure this one doesn't:
```python
resolve_patterns_locally_or_by_urls(
    base_path="/Users/quentinlhoest/Desktop/hf/datasets/playground",
    patterns=["*/data.txt"]
)
```

--------------

(and probably out of scope for now - not important)

maybe this one should return the file
```python
resolve_patterns_locally_or_by_urls(
    base_path="/Users/quentinlhoest/Desktop/hf/datasets/playground",
    patterns=[".yo/*"]
)
```

**Comment by mariosasko** [comment]
I'm aware of this behavior, which is tricky to solve due to fsspec's hidden file handling (see https://github.com/huggingface/datasets/issues/4115#issuecomment-1108819538). I've tested some regex patterns to address this, and they seem to work (will push them on Monday; btw they don't break any of fsspec's tests, so maybe we can contribute this enhancement to them). Also, perhaps we should include the files starting with `__`  in the results again (we hadn't had issues with this pattern before). WDYT?

**Comment by lhoestq** [comment]
I see. Feel free to merge this one if it's good for you btw :)

> Also, perhaps we should include the files starting with __ in the results again (we hadn't had issues with this pattern before)

The point was mainly to ignore __pycache__ directories for example. Also also for consistency with the iter_files/iter_archive which are already ignoring them

**Comment by mariosasko** [comment]
Very elegant solution! Feel free to merge if the CI is green after adding the tests.

**Comment by lhoestq** [comment]
CI failure is unrelated to this PR

**Pull request merged**
