### PR TITLE
HindEncorp again commited

### PR DESCRIPTION
**Pull request by rahul-art**

### CODE REVIEW

**Comment by yjernite** [comment]
Yes this has the right files!!!

I'll close the previous one then :) 

Now to pass the tests, you will need to:
- `make style` and run `flake8 datasets` from your repository root directory
- fix the dummy data

Did you generate the dummy data with the auto-generation tool (see the guide) or manually?

**Comment by rahul-art** [comment]
manually with the tool, it is not able to create

**Comment by yjernite** [comment]
Cool, in that case you need to pay special attention to the directory structure given to you by the tool, most failures are because the files are in the wrong directory or at the wrong level :) 

Also, make sure that the tests pass locally before pushing to the branch, it should help you get the structure right ;)

**Comment by rahul-art** [comment]
yes I have give proper directory structure datasets/hind_encorp/dummy/0.0.0/dummy_data.zip  but in my dummy_data.zip only 1 file hind_encorp.plaintext is present because the dataset I got has only 1 file with both English and Hindi languages on 1 file itself may be this is causing issue

**Comment by yjernite** [comment]
Looks like the name of the file is the issue here: you have a file called `hindencorp05.plaintext`, but it should be called `hindencorp05.plaintext.gz%3Fsequence%3D3%26isAllowed%3Dy`. You just have to rename it to pass the test:
```
cd datasets/hind_encorp/dummy/0.0.0
rm -rf dummy_data
unzip dummy_data.zip
rm dummy_data.zip
mv dummy_data/hindencorp05.plaintext "dummy_data/hindencorp05.plaintext.gz%3Fsequence%3D3%26isAllowed%3Dy"
zip -r dummy_data.zip dummy_data 
```

Then **once you pass the tests locally** you just have to remember to `make style` and `flake8 datasets` to pass the style checks, and you should be good to go :hugs: 

For reference, here are the instructions given by the tool:
```
$ python datasets-cli dummy_data datasets/hind_encorp/
2020-12-14 13:16:26.824828: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-12-14 13:16:26.824846: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using custom data configuration default

==============================DUMMY DATA INSTRUCTIONS==============================
- In order to create the dummy data for , please go into the folder 'datasets/hind_encorp/dummy/0.0.0' with `cd datasets/hind_encorp/dummy/0.0.0` . 

- Please create the following dummy data files 'dummy_data/hindencorp05.plaintext.gz%3Fsequence%3D3%26isAllowed%3Dy' from the folder 'datasets/hind_encorp/dummy/0.0.0'

- For each of the splits 'train', make sure that one or more of the dummy data files provide at least one example 

- If the method `_generate_examples(...)` includes multiple `open()` statements, you might have to create other files in addition to 'dummy_data/hindencorp05.plaintext.gz%3Fsequence%3D3%26isAllowed%3Dy'. In this case please refer to the `_generate_examples(...)` method 

-After all dummy data files are created, they should be zipped recursively to 'dummy_data.zip' with the command `zip -r dummy_data.zip dummy_data/` 

-You can now delete the folder 'dummy_data' with the command `rm -r dummy_data` 

- To get the folder 'dummy_data' back for further changes to the dummy data, simply unzip dummy_data.zip with the command `unzip dummy_data.zip` 

- Make sure you have created the file 'dummy_data.zip' in 'datasets/hind_encorp/dummy/0.0.0' 
===================================================================================
```

**Comment by rahul-art** [comment]
all test passed locally.   my  new  PR #1575

**Comment by lhoestq** [comment]
Closing this one in favor of #1575

**Pull request closed without merging**
