### PR TITLE
Kd conv smangrul

### PR DESCRIPTION
**Pull request by pacman100**

### CODE REVIEW

**Comment by ijaz314** [comment]
Hii please follow me

**Review by lhoestq — COMMENTED** [review]
Really cool thanks !

Before we merge, can you try to reduce the size of the dummy_data.zip files ?
Ideally they should all be below 10KB

To do so feel free to take a look inside them and remove unnecessary files and chunks of text.
Especially if there are long dialogues you can keep only the few sentences. Same for knowledge bases: only keep less than 10 entries if possible

**Review by lhoestq — APPROVED** [review]
Awesome thank you !

**Comment by lhoestq** [comment]
merging since the CI is fixed on master

**Pull request merged**
