### PR TITLE
Remove `HfFileSystem` and deprecate `S3FileSystem`

### PR DESCRIPTION
**Pull request by mariosasko**
Remove the legacy `HfFileSystem` and deprecate `S3FileSystem`

cc @philschmid for the SageMaker scripts/notebooks that still use `datasets`' `S3FileSystem`

### CODE REVIEW

**Comment by philschmid** [comment]
what would be the change i need to make?

**Comment by mariosasko** [comment]
@philschmid You just need to replace the occurrences of `datasets.filesystems.S3FileSystem` with `s3fs.S3FileSystem`. From the moment it was added until now, `datasets.filesystems.S3FileSystem` is a "dummy" subclass of `s3fs.S3FileSystem` that only changes its docstring.

**Review by lhoestq — APPROVED** [review]
LGTM :)

**Comment by lhoestq** [comment]
The CI is failing because I updated the YAML validation for https://github.com/huggingface/datasets/pull/6044.
It will be fixed once https://github.com/huggingface/datasets/pull/6044 is merged

**Comment by lhoestq** [comment]
I just merged the other PR so you should be good now

**Comment by mariosasko** [comment]
CI failure is unrelated. Merging.

**Pull request merged**
