### PR TITLE
Add Tweet Eval Dataset

### PR DESCRIPTION
**Pull request by abhishekkrthakur**

### CODE REVIEW

**Comment by gchhablani** [comment]
Hi @lhoestq,

Seeing that it has been almost two months to this draft, I'm willing to take this forward if you and @abhishekkrthakur don't mind. :)

**Comment by lhoestq** [comment]
Hi @gchhablani !
Sure if @abhishekkrthakur doesn't mind
Thanks for your help :)

**Comment by abhishekkrthakur** [comment]
Please fell free :)

**Comment by gchhablani** [comment]
Hi @lhoestq, @abhishekkrthakur 

I believe this can be closed. Merged in #1829.

**Pull request closed without merging**
