### PR TITLE
fix #2391 add original answers in kilt-TriviaQA

### LINKED ISSUE #2391: Missing original answers in kilt-TriviaQA
I previously opened an issue at https://github.com/facebookresearch/KILT/issues/42 but from the answer of @fabiopetroni it seems that the problem comes from HF-datasets

## Describe the bug
The `answer` field in kilt-TriviaQA, e.g. `kilt_tasks['train_triviaqa'][0]['output']['answer']` contains a list of alternative answer which are accepted for the question.  
However it'd be nice to know the original answer to the question (the only fields in `output` are `'answer', 'meta', 'provenance'`)

## How to fix
It can be fixed by retrieving the original answer from the original TriviaQA (e.g. `trivia_qa['train'][0]['answer']['value']`), perhaps at the same place as here where one retrieves the questions https://github.com/huggingface/datasets/blob/master/datasets/kilt_tasks/README.md#loading-the-kilt-knowledge-source-and-task-data

cc @yjernite who previously answered to an issue about KILT and TriviaQA :)

### PR DESCRIPTION
**Pull request by PaulLerner**
cc @yjernite is it ok like this?

### CODE REVIEW

**Comment by yjernite** [comment]
LGTM, but I'm not sure what's going on with the Unix tests @lhoestq

**Comment by lhoestq** [comment]
The CI error is unrelated to this PR, it's been fixed now on master.

**Comment by yjernite** [comment]
Thanks @PaulLerner !

**Comment by aDrIaNo34500** [comment]
> #- [ ] - Heyimage@fr[fr_fr**fr~~fr `fr```
FR
````~~**_]()

**Comment by lhoestq** [comment]
Oh that was unexpected. I didn't know pokemons were into NLP

**Pull request merged**
