### PR TITLE
Deprecate `use_auth_token` in favor of `token`

### PR DESCRIPTION
**Pull request by mariosasko**
... to be consistent with `transformers` and `huggingface_hub`.

### CODE REVIEW

**Review by lhoestq — COMMENTED** [review]
Cool ! AFAIK transformers and use_auth_token still uses `use_auth_token` for models no ? cc @LysandreJik

There is also the option of not having a deprecation message before we update all the scripts in `transformers`

**Comment by mariosasko** [comment]
They use `token` and emit a deprecation warning if use_auth_token is passed instead (see https://github.com/huggingface/transformers/blob/78a2b19fc84ed55c65f4bf20a901edb7ceb73c5f/src/transformers/modeling_utils.py#L1933).

**Comment by lhoestq** [comment]
> I think we can update the examples scripts after merging this PR.

We should do a release before updated in the examples scripts no ? That's why it's an option to not have a deprecation warning until transformers and co are updated with the `token` arg

**Comment by mariosasko** [comment]
> We should do a release before updated in the examples scripts no ? That's why it's an option to not have a deprecation warning until transformers and co are updated with the token arg

This would avoid the warning only for the latest `datasets` release. TBH, I don't think this is worth the hassle, considering how simple it is to remove it.

**Review by lhoestq — APPROVED** [review]
Looks all good then, let us know @LysandreJik if it sounds good to you

**Comment by LysandreJik** [comment]
Yes, sounds great! Thanks

**Review by julien-c — COMMENTED** [review]
note that anyways like transformers datasets already picks up the user's token automaticaly no?

**Comment by lhoestq** [comment]
yup

**Pull request merged**
