### PR TITLE
[fix]: iwslt2017 download urls

### LINKED ISSUE #2076: Issue: Dataset download error
The download link in `iwslt2017.py` file does not seem to work anymore.

For example, `FileNotFoundError: Couldn't find file at https://wit3.fbk.eu/archive/2017-01-trnted/texts/zh/en/zh-en.tgz`

Would be nice if we could modify it script and use the new downloadable link?

### PR DESCRIPTION
**Pull request by msarmi9**
Fixes #2076.

### CODE REVIEW

**Comment by msarmi9** [comment]
Oh, I found it just by following the link from the [IWSLT2017 homepage](https://wit3.fbk.eu/2017-01). Not sure if it's available from another host.

**Comment by lhoestq** [comment]
Ok cool ! I guess it's ok to use this URL for now, and we can see later if we need to change it.

Before merging, could you update the `dataset_infos.json` file by running this command please ?
```
datasets-cli test ./datasets/iwslt2017 --save_infos --all_configs
```

**Comment by msarmi9** [comment]
sure thing. lmk if there's anything else i can do to help.

**Comment by msarmi9** [comment]
just checking in. is there anything i can do to help on my end to get this merged? (the dummy data tests are failing due an incorrect path, i think)

**Comment by lhoestq** [comment]
Thanks ! I also fixed the dummy data :)

To fix the CI, feel free to merge the `master` branch into your PR.

If you have some time, feel free to also take a look at the missing YAML tags at the top of the README.md file of this dataset:
```
E           ValueError: The following issues have been found in the dataset cards:
E           YAML tags:
E           missing 9 required tags: 'annotations_creators', 'language_creators', 'languages', 'licenses', 'multilinguality', 'size_categories', 'source_datasets', 'task_categories', and 'task_ids'
```
you can use the dataset tagging app here: https://huggingface.co/spaces/huggingface/datasets-tagging

**Comment by albertvillanova** [comment]
I guess this PR was superseded by this other:
- #4481

Thanks for your contribution anyway, @msarmi9.

**Pull request closed without merging**
