### PR TITLE
add `desc` to `tqdm` in `Dataset.map()`

### LINKED ISSUE #2330: Allow passing `desc` to `tqdm` in `Dataset.map()`
It's normal to have many `map()` calls, and some of them can take a few minutes,
it would be nice to have a description on the progress bar.

Alternative solution:
Print the description before/after the `map()` call.

### PR DESCRIPTION
**Pull request by bhavitvyamalik**
Fixes #2330. Please let me know if anything is also required in this

### CODE REVIEW

**Comment by stas00** [comment]
Once this is merged, let's create an issue on `transformers` to update examples to use this new code. As currently all those tqdm bars are who knows what they are....

**Comment by bhavitvyamalik** [comment]
Sure @stas00! Once this is merged let's discuss what all changes can be done on `transformers` side

**Review by lhoestq — APPROVED** [review]
Thanks ! LGTM

**Comment by stas00** [comment]
@bhavitvyamalik, as it has been merged would you like to tackle https://github.com/huggingface/transformers/issues/11797?

**Comment by bhavitvyamalik** [comment]
Definitely @stas00. From what I could gather, you guys want more meaningful `.map` calls for all examples [here](https://github.com/huggingface/transformers/tree/master/examples/pytorch)?

**Comment by stas00** [comment]
That's exactly right, @bhavitvyamalik 

Perhaps the best approach is to do one example, see that other maintainers agree on it. and then replicate to other.

**Pull request merged**
