### PR TITLE
Add reasoning_bg

### PR DESCRIPTION
**Pull request by saradhix**
Adding reading comprehension dataset for Bulgarian language

### CODE REVIEW

**Review by lhoestq — COMMENTED** [review]
Thanks for adding this one !
Looks all good to me :) 

Could you just try to reduce the size of the dummy_data.zip files ? They're currently quite big (99KB each)

To do so feel free to take a look at the json file inside and remove as much unnecessary data as possible. For example for the dummy_data.zip file of the biology-12th config, you can remove the json field of the other configs like geography-12th.
You can also remove big chunks of text to only keep a few paragraphs.

**Comment by lhoestq** [comment]
Hi @saradhix have you had the chance to reduce the size of the dummy data ?

Feel free to ping me when it's done so we can merge :)

**Comment by saradhix** [comment]
@lhoestq I have reduced the size of the dummy data manually and pushed the changes.

**Comment by lhoestq** [comment]
The CI errors are not related to your dataset.
They're fixed on master, you can ignore them

**Review by lhoestq — APPROVED** [review]
Thank you ! Looks all good now :)

**Comment by lhoestq** [comment]
merging since the CI is fixed on master

**Pull request merged**
