### PR TITLE
Add SciTLDR Dataset (Take 2)

### PR DESCRIPTION
**Pull request by Bharat123rox**
Adds the SciTLDR Dataset by AI2
Added the `README.md` card with tags to the best of my knowledge

Multi-target summaries or TLDRs of Scientific Documents

Continued from #986

### CODE REVIEW

**Comment by Bharat123rox** [comment]
@lhoestq please review now

**Review by lhoestq — APPROVED** [review]
LGTM thank you !
(waiting for the CI to be all green to merge)

**Comment by lhoestq** [comment]
If the CI fails just because of `RemoteDatasetTest` errors it's fine, they're fixed on master

**Comment by Bharat123rox** [comment]
> If the CI fails just because of `RemoteDatasetTest` errors it's fine, they're fixed on master

The same 3 tests are failing again :(
```
FAILED tests/test_dataset_common.py::RemoteDatasetTest::test_builder_class_norwegian_ner
FAILED tests/test_dataset_common.py::RemoteDatasetTest::test_builder_configs_norwegian_ner
FAILED tests/test_dataset_common.py::RemoteDatasetTest::test_load_dataset_norwegian_ner
```

**Comment by lhoestq** [comment]
One trick if you want to add more datasets to avoid these errors : you can just rebase the master branch of your fork from the master branch of the repo. Then each time you make a new branch from master on your fork, it will include the fix for these errors

**Comment by Bharat123rox** [comment]
> One trick if you want to add more datasets to avoid these errors : you can just rebase the master branch of your fork from the master branch of the repo. Then each time you make a new branch from master on your fork, it will include the fix for these errors

Yes, I almost always do that, but somehow seems even this branch got old 😓 
I also do the following if I directly create a new branch locally: `git checkout -b <branchname> upstream/master` so it stays up-to date irrespective of my fork, still don't know how this crept in again

**Comment by lhoestq** [comment]
Merging this one since the CI is fixed on master

**Pull request merged**
