### PR TITLE
Add Sesotho Ner

### PR DESCRIPTION
**Pull request by yvonnegitau**

### CODE REVIEW

**Comment by lhoestq** [comment]
looks like this PR include changes to other files (sepedi)
could you try to only include the files related to the addition of sesotho ner ?

**Comment by yvonnegitau** [comment]
I think i need to clean up my local repo. I am committing everything a fresh after sepedi

**Comment by lhoestq** [comment]
Feel free to ping me when yuo have a clean PR and it's ready to review :)

**Comment by lhoestq** [comment]
closing in favor of #1114

**Pull request closed without merging**
