### PR TITLE
Remove default `trust_remote_code=True`

### PR DESCRIPTION
**Pull request by lhoestq**
TODO:
- [x] fix tests

### CODE REVIEW

**Comment by julien-c** [comment]
yay! 🎉

**Comment by henilp105** [comment]
@lhoestq Thanks for the PR, Is there a way to detect if `trust_remote_code=True` will be required for loading the dataset, without loading it? It would be great if you could please point me to the relevant documentation.

**Comment by lhoestq** [comment]
You can check the presence of a python loading script in the repository.

If there is a .py file named after the repository name, then it requires trust_remote_code.

**Comment by henilp105** [comment]
Thanks @lhoestq for the reference.

**Pull request merged**
