### PR TITLE
Add Neural Code Search Dataset

### PR DESCRIPTION
**Pull request by vinaykudari**

### CODE REVIEW

**Comment by vinaykudari** [comment]
@lhoestq Refactored into new branch, please review :)

**Comment by lhoestq** [comment]
The `RemoteDatasetTest ` errors in the CI are fixed on master so it's fine

**Review by lhoestq — APPROVED** [review]
Awesome thanks :)

**Comment by lhoestq** [comment]
merging since the CI is fixed on master

**Pull request merged**
