### PR TITLE
Move `exceptions.py` to `utils/exceptions.py`

### PR DESCRIPTION
**Pull request by mariosasko**
I didn't notice the path while reviewing the PR yesterday :(

### CODE REVIEW

**Review by albertvillanova — COMMENTED** [review]
I put the `exceptions` module at the root of the project in purpose because it is part of the public API.

Note that having the exceptions/errors module at the root is a common pattern followed in many open-source libraries, like `numpy`, `pandas`, `pyarrow`, `requests`...

**Review by albertvillanova — COMMENTED** [review]
Maybe we could ask `huggingface_hub` to align with the rest of open-source libraries and expose the errors/exceptions at the root of the library...

```python
In [11]: requests.ConnectionError
Out[11]: requests.exceptions.ConnectionError

In [12]: pandas.errors.ClosedFileError
Out[12]: pandas.errors.ClosedFileError

In [13]: numpy.AxisError  # defined in numpy/exceptions.py
Out[13]: numpy.AxisError

In [14]: pyarrow.ArrowKeyError  # defined in pyarrow/error.pxi
Out[14]: pyarrow.lib.ArrowKeyError
```

**Comment by Wauplin** [comment]
I can expose exceptions at root level yes.

About having guidelines and consistency, let's try to do our best but it's not really in the essence of HF to formalize stuff in libraries :unamused:

**Comment by Wauplin** [comment]
Better late than never, we now have all the exceptions defined in `huggingface_hub.errors`! See https://github.com/huggingface/huggingface_hub/issues/2069.

**Comment by albertvillanova** [comment]
Thanks for taking care, @Wauplin. I am closing this PR.

**Pull request closed without merging**
