### PR TITLE
Add twi text c3

### PR DESCRIPTION
**Pull request by dadelani**
Added Twi texts for training embeddings and language models based on the paper https://www.aclweb.org/anthology/2020.lrec-1.335/

### CODE REVIEW

**Comment by lhoestq** [comment]
looks like this PR includes changes about other datasets

Can you only include the changes related to twi text c3 please ?

**Comment by dadelani** [comment]
Hi @lhoestq , I have removed the unnecessary files. Can you please confirm?

**Comment by cstorm125** [comment]
You might need to either find a way to go back to the commit before it changes 389 files or create a new branch.

**Comment by dadelani** [comment]
okay, I have created another branch, see the latest pull https://github.com/huggingface/datasets/pull/1518  @cstorm125

**Comment by ijaz314** [comment]
Hii please follow me

**Comment by lhoestq** [comment]
Closing this one in favor of #1518

**Pull request closed without merging**
