### PR TITLE
Modify add_column() to optionally accept a FeatureType as param

### PR DESCRIPTION
**Pull request by varadhbhatnagar**
[Open Issue](https://github.com/huggingface/datasets/issues/7142)

**Before (Add + Cast)**:

```
from datasets import load_dataset, Value
ds = load_dataset("rotten_tomatoes", split="test")
lst = [i for i in range(len(ds))]

ds = ds.add_column("new_col", lst)
# Assigns int64 to new_col by default
print(ds.features)

ds = ds.cast_column("new_col", Value(dtype="uint16", id=None))
print(ds.features)
```

**Before (Numpy Workaround)**:

```
from datasets import load_dataset
import numpy as np
ds = load_dataset("rotten_tomatoes", split="test")
lst = [i for i in range(len(ds))]

ds = ds.add_column("new_col", np.array(lst, dtype=np.uint16))
print(ds.features)
```

**After**:
```
from datasets import load_dataset, Value
ds = load_dataset("rotten_tomatoes", split="test")
lst = [i for i in range(len(ds))]
val = Value(dtype="uint16", id=None))
ds = ds.add_column("new_col", lst, feature=val)
print(ds.features)
```

### CODE REVIEW

**Comment by varadhbhatnagar** [comment]
Requesting review @lhoestq 
I will also update the docs if this looks good.

**Comment by lhoestq** [comment]
Cool ! maybe you can rename the argument `feature` and with type `FeatureType` ? This way it would work the same way as `.cast_column()` ?

**Review by lhoestq — COMMENTED** [review]
LGTM ! Can you just add the `feature` argument to the docstrings before we merge ?

**Comment by varadhbhatnagar** [comment]
@lhoestq done!

**Comment by varadhbhatnagar** [comment]
@lhoestq anything pending on this?

**Review by lhoestq — APPROVED** [review]
Thanks ! LGTM :)

**Pull request merged**
