### PR TITLE
Added Times of India News Headlines Dataset

### PR DESCRIPTION
**Pull request by tanmoyio**
Dataset name: Times of India News Headlines
link: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/DPQMQH

### CODE REVIEW

**Comment by tanmoyio** [comment]
@lhoestq @abhishekkrthakur what happened here ?

**Comment by tanmoyio** [comment]
@lhoestq everything alright here ?

**Comment by abhishekkrthakur** [comment]
@tanmoyio please have patience. @lhoestq has to look at 150+ PRs and it may take time. The PR looks good to me but we wait for his confirmation :) 🤗

**Review by lhoestq — APPROVED** [review]
Sorry for the delay ;) 

Looks all good to me, thank you !

**Pull request merged**
