### PR TITLE
less script docs

### PR DESCRIPTION
**Pull request by lhoestq**
+ mark as legacy in some parts of the docs since we'll not build new features for script datasets

### CODE REVIEW

**Review by albertvillanova — APPROVED** [review]
Thanks.

**Comment by mayorblock** [comment]
Hi @lhoestq,

I was confused by `legacy` prefix added to the [image data loading](https://huggingface.co/docs/datasets/main/en/image_dataset#legacy-loading-script) script section. I have a custom image dataset and have looked through the documentation to find something similar but can't find a good alternative What is now the recommend way to create a custom image dataset then? I want the HF format but will not host it on the hub.

Apologies in advance if this is the wrong place to ask such questions...

**Comment by lhoestq** [comment]
We stopped making new features for datasets with scripts for obvious security reasons, that's why they are marked as "legacy". What is blocking you from hosting on HF ?

**Comment by mayorblock** [comment]
Hi, thanks for the prompt answer :) I am working on proprietary datasets for the company where I am employed. We want to keep the data in-house but would like to investigate the use of the HF ecosystem.

**Pull request merged**
