### PR TITLE
Add tqdm arguments

### PR DESCRIPTION
**Pull request by penguinwang96825**
In this PR, tqdm arguments can be passed to the map() function and such, in order to be more flexible.

### CODE REVIEW

**Comment by lhoestq** [comment]
Hi ! Thanks this will be very useful :)

It looks like there are some changes in the github diff that are not related to your contribution, can you try fixing this by merging `master` into your PR, or create a new PR from an updated version of `master` ?

**Comment by penguinwang96825** [comment]
I have already solved the conflict on this latest version. This is my first time sending PR, if there's anything I need to adjust just let me know~

**Comment by lhoestq** [comment]
Thanks, most changes are gone :)
It still seems to include changes though - do you mind try creating a new branch from upstream/master and create a new PR please ?

**Comment by penguinwang96825** [comment]
Yeah sure, I'll try to send a new PR today!

**Comment by penguinwang96825** [comment]
Please forward to [#3850](https://github.com/huggingface/datasets/pull/3850)

**Comment by lhoestq** [comment]
Thanks ! Closing this one in favor of https://github.com/huggingface/datasets/pull/3850/files

**Pull request closed without merging**
