### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mayank1897**

### CODE REVIEW

**Comment by KabirKwatra** [comment]
Hacktoberfest spam

**Comment by mayank1897** [comment]
To enhance its readability.....not Hacktoberfest spam

**Comment by JoeyStrandnes** [comment]
How is adding a punctuation to the end of a sentence justified as "To enhance its readability". 
Considering that this is not your first "README enhancement '' please don't spam the open source community with useless PR to get a free T-Shirt it just hurts the maintainers.

//Joey

**Comment by julien-c** [comment]
closed as spam

**Pull request closed without merging**
