### PR TITLE
Add PEC

### PR DESCRIPTION
**Pull request by zhongpeixiang**
A persona-based empathetic conversation dataset.

### CODE REVIEW

**Comment by zhongpeixiang** [comment]
I'm a bit frustrating now to get this right.

**Review by sumanthd17 — COMMENTED** [review]
The CI pipeline is failing for other dataset

run 
`git fetch upstream`
`git rebase upstream/master`

That should solve the CI pipeline failing issue

**Review by lhoestq — APPROVED** [review]
Very clean !
Thank you so much for adding this one, good job :)

**Comment by thomwolf** [comment]
Hey @zhongpeixiang!
Really nice addition here!

Did you officially joined the sprint by posting [on the forum thread](https://discuss.huggingface.co/t/open-to-the-community-one-week-team-effort-to-reach-v2-0-of-hf-datasets-library/2176) and joining our slack?
I can't seem to find you there! Should I add you directly with your gmail address?

**Comment by zhongpeixiang** [comment]
> Hey @zhongpeixiang!
> Really nice addition here!
> 
> Did you officially joined the sprint by posting [on the forum thread](https://discuss.huggingface.co/t/open-to-the-community-one-week-team-effort-to-reach-v2-0-of-hf-datasets-library/2176) and joining our slack?
> I can't seem to find you there! Should I add you directly with your gmail address?

Thank you for the invitation. This initiative is awesome. Sadly I’m occupied by my thesis writing this month. Good luck 🤗

**Comment by thomwolf** [comment]
As you want @zhongpeixiang (I was maybe not clear but that just mean that by posting on the forum thread that you participated in the current event you will get a special gift for the contribution that you have already done here :-) Nothing more to do)

**Comment by zhongpeixiang** [comment]
> As you want @zhongpeixiang (I was maybe not clear but that just mean that by posting on the forum thread that you participated in the current event you will get a special gift (a tee-shirt) for the contribution that you have already done here :-) Nothing more to do)

Oh, I misunderstood the post. I'm glad to join.

**Pull request merged**
