### PR TITLE
add `desc` in `map` for `DatasetDict` object

### PR DESCRIPTION
**Pull request by bhavitvyamalik**
`desc` in `map` currently only works with `Dataset` objects. This PR adds support for `DatasetDict` objects as well

### CODE REVIEW

**Review by lhoestq — APPROVED** [review]
Great thank you :)

**Comment by lhoestq** [comment]
The CI error is unrelated to the PR, merging

**Comment by bhavitvyamalik** [comment]
@lhoestq, can we release this feature if you guys are planning for any patch release for Datasets. It'll slow down [#11927](https://github.com/huggingface/transformers/pull/11927) otherwise :/

**Comment by lhoestq** [comment]
Sure definitely, having a discrepancy between Dataset.map and DatasetDict.map is an issue that we should fix and include in a patch release. Will it in the coming days

**Pull request merged**
