### PR TITLE
Re-add download_manager module in utils

### PR DESCRIPTION
**Pull request by lhoestq**
https://github.com/huggingface/datasets/pull/4384 moved `datasets.utils.download_manager` to `datasets.download.download_manager`

This breaks `evaluate` which imports `DownloadMode` from `datasets.utils.download_manager` 

This PR re-adds `datasets.utils.download_manager` without circular imports.

We could also show a message that says that accessing it is deprecated, but I think we can do this in a subsequent PR, and just focus on doing a patch release for now

### CODE REVIEW

**Comment by albertvillanova** [comment]
Thanks for the fix.

I'm wondering how this fixes backward compatibility...

Executing this code:
```python
from datasets.utils.download_manager import DownloadMode
```
we will have
```python
DownloadMode = None
```

If afterwards we use something like:
```python
if download_mode == DownloadMode.FORCE_REDOWNLOAD
```
that will raise an exception.

**Comment by lhoestq** [comment]
It works fine on my side:
```python
>>> from datasets.utils.download_manager import DownloadMode
>>> DownloadMode is not None
True
```

**Comment by lhoestq** [comment]
As reported in https://github.com/huggingface/evaluate/pull/143
```
from datasets.utils import DownloadConfig
```
is also missing, I'm re-adding it

**Comment by lhoestq** [comment]
Took the liberty of merging this one, to do a patch release soon. If we think of a better approach we can improve it later

**Pull request merged**
