### PR TITLE
Update metadata if dataset features are modified

### LINKED ISSUE #2083: `concatenate_datasets` throws error when changing the order of datasets to concatenate
Hey, 

I played around with the `concatenate_datasets(...)` function: https://huggingface.co/docs/datasets/package_reference/main_classes.html?highlight=concatenate_datasets#datasets.concatenate_datasets

and noticed that when the order in which the datasets are concatenated changes an error is thrown where it should not IMO.

Here is a google colab to reproduce the error: https://colab.research.google.com/drive/17VTFU4KQ735-waWZJjeOHS6yDTfV5ekK?usp=sharing

### PR DESCRIPTION
**Pull request by mariosasko**
This PR adds a decorator that updates the dataset metadata if a previously executed transform modifies its features. 
Fixes #2083

### CODE REVIEW

**Comment by mariosasko** [comment]
@lhoestq I'll try to add a test later if you think this approach with the wrapper is good.

**Comment by lhoestq** [comment]
Awesome thank you !
Yes this approach with a wrapper is good :)

**Comment by mariosasko** [comment]
@lhoestq Added a test. To verify that this change fixes the problem, replace:
```
!pip install datasets==1.5
```
with:
```
!pip install git+https://github.com/mariosasko/datasets-1.git@update-metadata
```
in the first cell of the notebook that is attached to the linked issue.

The CI failure is unrelated I think (building the docs locally doesn't throw an error).

**Review by lhoestq — APPROVED** [review]
LGTM thank you !

**Comment by lhoestq** [comment]
The CI fail for the docs has been fixed on master.
Merging :)

**Pull request merged**
