### PR TITLE
[WIP][Test, Please ignore] Investigate performance impact of using multiprocessing only

### PR DESCRIPTION
**Pull request by hvaara**

### CODE REVIEW

**Comment by mariosasko** [comment]
`multiprocess` uses `dill` instead of `pickle` for pickling shared objects and, as such, can pickle more types than `multiprocessing`. And I don't think this is something we want to change :).

**Comment by hvaara** [comment]
That makes sense to me, and I don't think you should merge this change. I was only curious about the performance impact. I saw the benchmarks that was produced in other PRs, and wanted to get a better understanding of it. I created this PR to see if it got automatically added here.

Is there a way I can generate those benchmarks myself?

**Comment by mariosasko** [comment]
You can find some speed comparisons between dill and pickle on SO if you google "dill vs pickle speed".

And for the benchmarks, you can generate them locally with DVC running this code from the repo root: https://github.com/huggingface/datasets/blob/0803a006db1c395ac715662cc6079651f77c11ea/.github/workflows/benchmarks.yaml#L23-L47.

**Comment by hvaara** [comment]
Thanks for the help @mariosasko!

**Pull request closed without merging**
