### PR TITLE
Update tasks.json

### PR DESCRIPTION
**Pull request by sayakpaul**
Context:

* https://github.com/huggingface/datasets/issues/5255#issuecomment-1339107195

Cc: @osanseviero

### CODE REVIEW

**Comment by sayakpaul** [comment]
> I think the only place where we need to add it is here https://github.com/huggingface/hub-docs/blob/main/js/src/lib/interfaces/Types.ts
> 
> And I think we can remove tasks.json completely from this repo

What about the warning I mentioned in https://github.com/huggingface/datasets/issues/5255#issuecomment-1339013527? Also, the depth estimation entry is already present in https://github.com/huggingface/hub-docs/blob/main/js/src/lib/interfaces/Types.ts.

**Review by albertvillanova — COMMENTED** [review]
Hi @sayakpaul,

Please note that `depth-estimation` is defined as a possible value for `class_categories`, not for `class_ids`. You should set instead:
```yaml
task_categories:
- depth-estimation
```

We no longer use `tasks.json` file.

**Comment by sayakpaul** [comment]
The update is based on what I received in the output of the export job (c.f. https://github.com/huggingface/datasets/issues/5255#issuecomment-1339107195).

**Comment by albertvillanova** [comment]
Yes, my suggestion was for the dataset card: you got the error message because you tried to set `depth-estimation` in `class_ids` instead of `class_categories`.

**Comment by julien-c** [comment]
yes i would suggest rm'ing tasks.json here for clarity

**Comment by sayakpaul** [comment]
Closing it.

**Comment by lhoestq** [comment]
It's not clear if we can remove it btw, since old versions of `evaluate` rely on it (see https://github.com/huggingface/evaluate/pull/309)

cc @lvwerra

**Comment by lhoestq** [comment]
Actually it can be removed without incidence in old versions of evaluate since we kept an hardcoded `known_task_ids` that is marked "DEPRECATED"

**Pull request closed without merging**
