### PR TITLE
Fixes #5757

### LINKED ISSUE #5757: Tilde (~) is not supported
### Describe the bug

It seems that `~` is not recognized correctly in local paths. Whenever I try to use it I get an exception

### Steps to reproduce the bug

```python

load_dataset("imagefolder", data_dir="~/data/my_dataset")

```

Will generate the following error:
``` 
EmptyDatasetError: The directory at /path/to/cwd/~/data/datasets/clementine_tagged_per_cam doesn't contain any data files
```

### Expected behavior

Load the dataset.

### Environment info

datasets==2.11.0

### PR DESCRIPTION
**Pull request by eli-osherovich**
Fixes the bug #5757

### CODE REVIEW

**Review by lhoestq — APPROVED** [review]
Thanks for the fix !

**Comment by lhoestq** [comment]
The CI can be fixed by merging `main` into your branch. Can you do that before we merge ?

**Comment by eli-osherovich** [comment]
Done.

**Comment by lhoestq** [comment]
Nice thanks !

**Pull request merged**
