### PR TITLE
Add twi wordsim353

### PR DESCRIPTION
**Pull request by dadelani**
Added the citation information to the README file

### CODE REVIEW

**Review by lhoestq — APPROVED** [review]
Very nice thank you !
LGTM

**Comment by lhoestq** [comment]
Well actually it looks like it was already added in #1428 

Maybe we can close this one ? Or you wanted to make changes to this dataset ?

**Comment by dadelani** [comment]
Thank you, it's just a modification of Readme. I added the missing citation.

**Comment by lhoestq** [comment]
Indeed thanks

**Pull request merged**
